"""Core module - fundamental concepts shared across Skyward.

Contains exceptions, constants, events, and callback system.
"""

from skyward.core.callback import (
    Callback,
    CallbackResult,
    compose,
    emit,
    flush,
    use_callback,
)
from skyward.core.constants import (
    COMPRESSED_MAGIC,
    COMPRESSION_LEVEL,
    DEFAULT_INSTANCE_NAME,
    DEFAULT_PYTHON,
    INSTANCE_RUNNING_MAX_ATTEMPTS,
    INSTANCE_RUNNING_WAIT_DELAY,
    RPYC_PORT,
    SKYWARD_DIR,
    SSM_AGENT_TIMEOUT,
    UV_INSTALL_URL,
    VENV_DIR,
    InstanceState,
    SkywardTag,
)
from skyward.core.events import (
    BootstrapCompleted,
    BootstrapProgress,
    BootstrapStarting,
    CostFinal,
    CostUpdate,
    Error,
    FunctionCall,
    FunctionResult,
    InstanceLaunching,
    InstanceProvisioned,
    InstanceReady,
    InstanceStopping,
    LogLine,
    Metrics,
    NetworkReady,
    PoolReady,
    PoolStarted,
    PoolStopping,
    ProviderName,
    ProvisionedInstance,
    ProvisioningCompleted,
    ProvisioningStarted,
    RegionAutoSelected,
    SkywardEvent,
)
from skyward.core.exceptions import (
    ConfigurationError,
    ConnectionError,
    ConnectionLostError,
    ExecutionError,
    InstanceTerminatedError,
    NoMatchingInstanceError,
    NotProvisionedError,
    ProvisioningError,
    SerializationError,
    SkywardError,
    TimeoutError,
)

__all__ = [
    # Exceptions
    "SkywardError",
    "NotProvisionedError",
    "ProvisioningError",
    "NoMatchingInstanceError",
    "ExecutionError",
    "SerializationError",
    "ConfigurationError",
    "TimeoutError",
    "ConnectionError",
    "InstanceTerminatedError",
    "ConnectionLostError",
    # Constants
    "SkywardTag",
    "InstanceState",
    "SKYWARD_DIR",
    "VENV_DIR",
    "UV_INSTALL_URL",
    "DEFAULT_PYTHON",
    "RPYC_PORT",
    "SSM_AGENT_TIMEOUT",
    "INSTANCE_RUNNING_WAIT_DELAY",
    "INSTANCE_RUNNING_MAX_ATTEMPTS",
    "DEFAULT_INSTANCE_NAME",
    "COMPRESSED_MAGIC",
    "COMPRESSION_LEVEL",
    # Events
    "ProviderName",
    "ProvisionedInstance",
    "ProvisioningStarted",
    "NetworkReady",
    "InstanceLaunching",
    "InstanceProvisioned",
    "ProvisioningCompleted",
    "RegionAutoSelected",
    "BootstrapStarting",
    "BootstrapProgress",
    "BootstrapCompleted",
    "InstanceReady",
    "Metrics",
    "LogLine",
    "FunctionCall",
    "FunctionResult",
    "InstanceStopping",
    "CostUpdate",
    "CostFinal",
    "PoolReady",
    "PoolStarted",
    "PoolStopping",
    "Error",
    "SkywardEvent",
    # Callback
    "Callback",
    "CallbackResult",
    "emit",
    "flush",
    "compose",
    "use_callback",
]
