"""Typed factories for every accelerator in the catalog.

Generated by ``scripts/gen_accelerators_pyi.py`` from
``skyward.protocol.accelerators.CATALOG`` — do not edit by hand.
"""

from collections.abc import Callable
from dataclasses import dataclass

@dataclass(frozen=True, slots=True)
class Accelerator:
    """A canonical accelerator name and how many of them a node should have."""

    name: str
    count: int = 1


def A10(count: int = 1) -> Accelerator:
    """A10, 24 GB VRAM."""
    ...

def A100(count: int = 1) -> Accelerator:
    """A100, 80 GB VRAM."""
    ...

def A100X(count: int = 1) -> Accelerator:
    """A100X, 80 GB VRAM."""
    ...

def A10G(count: int = 1) -> Accelerator:
    """A10G, 24 GB VRAM."""
    ...

def A16(count: int = 1) -> Accelerator:
    """A16, 16 GB VRAM."""
    ...

def A2(count: int = 1) -> Accelerator:
    """A2, 16 GB VRAM."""
    ...

def A30(count: int = 1) -> Accelerator:
    """A30, 24 GB VRAM."""
    ...

def A40(count: int = 1) -> Accelerator:
    """A40, 48 GB VRAM."""
    ...

def A800(count: int = 1) -> Accelerator:
    """A800, 80 GB VRAM."""
    ...

def B100(count: int = 1) -> Accelerator:
    """B100, 192 GB VRAM."""
    ...

def B200(count: int = 1) -> Accelerator:
    """B200, 192 GB VRAM."""
    ...

def B300(count: int = 1) -> Accelerator:
    """B300, 288 GB VRAM."""
    ...

def CMP_50HX(count: int = 1) -> Accelerator:
    """CMP-50HX, 10 GB VRAM."""
    ...

def GAUDI(count: int = 1) -> Accelerator:
    """GAUDI, 32 GB VRAM."""
    ...

def GAUDI2(count: int = 1) -> Accelerator:
    """GAUDI2, 96 GB VRAM."""
    ...

def GAUDI3(count: int = 1) -> Accelerator:
    """GAUDI3, 128 GB VRAM."""
    ...

def GB200(count: int = 1) -> Accelerator:
    """GB200, 384 GB VRAM."""
    ...

def GB300(count: int = 1) -> Accelerator:
    """GB300, 288 GB VRAM."""
    ...

def GH200(count: int = 1) -> Accelerator:
    """GH200, 96 GB VRAM."""
    ...

def GTX_1050(count: int = 1) -> Accelerator:
    """GTX-1050, 2 GB VRAM."""
    ...

def GTX_1050TI(count: int = 1) -> Accelerator:
    """GTX-1050TI, 4 GB VRAM."""
    ...

def GTX_1060(count: int = 1) -> Accelerator:
    """GTX-1060, 6 GB VRAM."""
    ...

def GTX_1070(count: int = 1) -> Accelerator:
    """GTX-1070, 8 GB VRAM."""
    ...

def GTX_1070TI(count: int = 1) -> Accelerator:
    """GTX-1070TI, 8 GB VRAM."""
    ...

def GTX_1080(count: int = 1) -> Accelerator:
    """GTX-1080, 8 GB VRAM."""
    ...

def GTX_1080TI(count: int = 1) -> Accelerator:
    """GTX-1080TI, 11 GB VRAM."""
    ...

def GTX_1650(count: int = 1) -> Accelerator:
    """GTX-1650, 4 GB VRAM."""
    ...

def GTX_1660(count: int = 1) -> Accelerator:
    """GTX-1660, 6 GB VRAM."""
    ...

def GTX_1660SUPER(count: int = 1) -> Accelerator:
    """GTX-1660SUPER, 6 GB VRAM."""
    ...

def GTX_1660TI(count: int = 1) -> Accelerator:
    """GTX-1660TI, 6 GB VRAM."""
    ...

def H100(count: int = 1) -> Accelerator:
    """H100, 80 GB VRAM."""
    ...

def H100_NVL(count: int = 1) -> Accelerator:
    """H100-NVL, 94 GB VRAM."""
    ...

def H200(count: int = 1) -> Accelerator:
    """H200, 141 GB VRAM."""
    ...

def H200_NVL(count: int = 1) -> Accelerator:
    """H200-NVL, 141 GB VRAM."""
    ...

def INFERENTIA1(count: int = 1) -> Accelerator:
    """INFERENTIA1, 8 GB VRAM."""
    ...

def INFERENTIA2(count: int = 1) -> Accelerator:
    """INFERENTIA2, 32 GB VRAM."""
    ...

def INSTINCT_MI25(count: int = 1) -> Accelerator:
    """INSTINCT-MI25, 16 GB VRAM."""
    ...

def K80(count: int = 1) -> Accelerator:
    """K80, 12 GB VRAM."""
    ...

def L4(count: int = 1) -> Accelerator:
    """L4, 24 GB VRAM."""
    ...

def L40(count: int = 1) -> Accelerator:
    """L40, 48 GB VRAM."""
    ...

def L40S(count: int = 1) -> Accelerator:
    """L40S, 48 GB VRAM."""
    ...

def MI100(count: int = 1) -> Accelerator:
    """MI100, 32 GB VRAM."""
    ...

def MI210(count: int = 1) -> Accelerator:
    """MI210, 64 GB VRAM."""
    ...

def MI250(count: int = 1) -> Accelerator:
    """MI250, 128 GB VRAM."""
    ...

def MI250X(count: int = 1) -> Accelerator:
    """MI250X, 128 GB VRAM."""
    ...

def MI300A(count: int = 1) -> Accelerator:
    """MI300A, 128 GB VRAM."""
    ...

def MI300B(count: int = 1) -> Accelerator:
    """MI300B, 192 GB VRAM."""
    ...

def MI300X(count: int = 1) -> Accelerator:
    """MI300X, 192 GB VRAM."""
    ...

def MI325X(count: int = 1) -> Accelerator:
    """MI325X, 256 GB VRAM."""
    ...

def MI355X(count: int = 1) -> Accelerator:
    """MI355X, 288 GB VRAM."""
    ...

def MI50(count: int = 1) -> Accelerator:
    """MI50, 16 GB VRAM."""
    ...

def P100(count: int = 1) -> Accelerator:
    """P100, 16 GB VRAM."""
    ...

def P4(count: int = 1) -> Accelerator:
    """P4, 8 GB VRAM."""
    ...

def P40(count: int = 1) -> Accelerator:
    """P40, 24 GB VRAM."""
    ...

def QUADRO_P2000(count: int = 1) -> Accelerator:
    """QUADRO-P2000, 5 GB VRAM."""
    ...

def QUADRO_P4000(count: int = 1) -> Accelerator:
    """QUADRO-P4000, 8 GB VRAM."""
    ...

def QUADRO_RTX_4000(count: int = 1) -> Accelerator:
    """QUADRO-RTX-4000, 8 GB VRAM."""
    ...

def QUADRO_RTX_5000(count: int = 1) -> Accelerator:
    """QUADRO-RTX-5000, 16 GB VRAM."""
    ...

def QUADRO_RTX_6000(count: int = 1) -> Accelerator:
    """QUADRO-RTX-6000, 24 GB VRAM."""
    ...

def QUADRO_RTX_8000(count: int = 1) -> Accelerator:
    """QUADRO-RTX-8000, 48 GB VRAM."""
    ...

def RADEON_PRO_V520(count: int = 1) -> Accelerator:
    """RADEON-PRO-V520, 8 GB VRAM."""
    ...

def RADEON_PRO_V710(count: int = 1) -> Accelerator:
    """RADEON-PRO-V710, 16 GB VRAM."""
    ...

def RTX_2000ADA(count: int = 1) -> Accelerator:
    """RTX-2000ADA, 16 GB VRAM."""
    ...

def RTX_2060(count: int = 1) -> Accelerator:
    """RTX-2060, 6 GB VRAM."""
    ...

def RTX_2060SUPER(count: int = 1) -> Accelerator:
    """RTX-2060SUPER, 8 GB VRAM."""
    ...

def RTX_2070(count: int = 1) -> Accelerator:
    """RTX-2070, 8 GB VRAM."""
    ...

def RTX_2070SUPER(count: int = 1) -> Accelerator:
    """RTX-2070SUPER, 8 GB VRAM."""
    ...

def RTX_2080(count: int = 1) -> Accelerator:
    """RTX-2080, 8 GB VRAM."""
    ...

def RTX_2080SUPER(count: int = 1) -> Accelerator:
    """RTX-2080SUPER, 8 GB VRAM."""
    ...

def RTX_2080TI(count: int = 1) -> Accelerator:
    """RTX-2080TI, 11 GB VRAM."""
    ...

def RTX_3050(count: int = 1) -> Accelerator:
    """RTX-3050, 8 GB VRAM."""
    ...

def RTX_3060(count: int = 1) -> Accelerator:
    """RTX-3060, 12 GB VRAM."""
    ...

def RTX_3060LAPTOP(count: int = 1) -> Accelerator:
    """RTX-3060LAPTOP, 6 GB VRAM."""
    ...

def RTX_3060TI(count: int = 1) -> Accelerator:
    """RTX-3060TI, 8 GB VRAM."""
    ...

def RTX_3070(count: int = 1) -> Accelerator:
    """RTX-3070, 8 GB VRAM."""
    ...

def RTX_3070TI(count: int = 1) -> Accelerator:
    """RTX-3070TI, 8 GB VRAM."""
    ...

def RTX_3080(count: int = 1) -> Accelerator:
    """RTX-3080, 10 GB VRAM."""
    ...

def RTX_3080TI(count: int = 1) -> Accelerator:
    """RTX-3080TI, 12 GB VRAM."""
    ...

def RTX_3090(count: int = 1) -> Accelerator:
    """RTX-3090, 24 GB VRAM."""
    ...

def RTX_3090TI(count: int = 1) -> Accelerator:
    """RTX-3090TI, 24 GB VRAM."""
    ...

def RTX_4000ADA(count: int = 1) -> Accelerator:
    """RTX-4000ADA, 20 GB VRAM."""
    ...

def RTX_4060(count: int = 1) -> Accelerator:
    """RTX-4060, 8 GB VRAM."""
    ...

def RTX_4060TI(count: int = 1) -> Accelerator:
    """RTX-4060TI, 8 GB VRAM."""
    ...

def RTX_4070(count: int = 1) -> Accelerator:
    """RTX-4070, 12 GB VRAM."""
    ...

def RTX_4070SUPER(count: int = 1) -> Accelerator:
    """RTX-4070SUPER, 12 GB VRAM."""
    ...

def RTX_4070TI(count: int = 1) -> Accelerator:
    """RTX-4070TI, 12 GB VRAM."""
    ...

def RTX_4070TISUPER(count: int = 1) -> Accelerator:
    """RTX-4070TISUPER, 16 GB VRAM."""
    ...

def RTX_4080(count: int = 1) -> Accelerator:
    """RTX-4080, 16 GB VRAM."""
    ...

def RTX_4080SUPER(count: int = 1) -> Accelerator:
    """RTX-4080SUPER, 16 GB VRAM."""
    ...

def RTX_4090(count: int = 1) -> Accelerator:
    """RTX-4090, 24 GB VRAM."""
    ...

def RTX_4090D(count: int = 1) -> Accelerator:
    """RTX-4090D, 24 GB VRAM."""
    ...

def RTX_4500ADA(count: int = 1) -> Accelerator:
    """RTX-4500ADA, 24 GB VRAM."""
    ...

def RTX_5000ADA(count: int = 1) -> Accelerator:
    """RTX-5000ADA, 32 GB VRAM."""
    ...

def RTX_5060(count: int = 1) -> Accelerator:
    """RTX-5060, 8 GB VRAM."""
    ...

def RTX_5060TI(count: int = 1) -> Accelerator:
    """RTX-5060TI, 16 GB VRAM."""
    ...

def RTX_5070(count: int = 1) -> Accelerator:
    """RTX-5070, 12 GB VRAM."""
    ...

def RTX_5070TI(count: int = 1) -> Accelerator:
    """RTX-5070TI, 16 GB VRAM."""
    ...

def RTX_5080(count: int = 1) -> Accelerator:
    """RTX-5080, 16 GB VRAM."""
    ...

def RTX_5090(count: int = 1) -> Accelerator:
    """RTX-5090, 32 GB VRAM."""
    ...

def RTX_5880ADA(count: int = 1) -> Accelerator:
    """RTX-5880ADA, 48 GB VRAM."""
    ...

def RTX_6000ADA(count: int = 1) -> Accelerator:
    """RTX-6000ADA, 48 GB VRAM."""
    ...

def RTX_A2000(count: int = 1) -> Accelerator:
    """RTX-A2000, 12 GB VRAM."""
    ...

def RTX_A4000(count: int = 1) -> Accelerator:
    """RTX-A4000, 16 GB VRAM."""
    ...

def RTX_A4500(count: int = 1) -> Accelerator:
    """RTX-A4500, 20 GB VRAM."""
    ...

def RTX_A5000(count: int = 1) -> Accelerator:
    """RTX-A5000, 24 GB VRAM."""
    ...

def RTX_A5000PRO(count: int = 1) -> Accelerator:
    """RTX-A5000PRO, 24 GB VRAM."""
    ...

def RTX_A6000(count: int = 1) -> Accelerator:
    """RTX-A6000, 48 GB VRAM."""
    ...

def RTX_PRO_4000(count: int = 1) -> Accelerator:
    """RTX-PRO-4000, 24 GB VRAM."""
    ...

def RTX_PRO_4500(count: int = 1) -> Accelerator:
    """RTX-PRO-4500, 32 GB VRAM."""
    ...

def RTX_PRO_5000(count: int = 1) -> Accelerator:
    """RTX-PRO-5000, 48 GB VRAM."""
    ...

def RTX_PRO_6000(count: int = 1) -> Accelerator:
    """RTX-PRO-6000, 96 GB VRAM."""
    ...

def RTX_PRO_6000MAXQ(count: int = 1) -> Accelerator:
    """RTX-PRO-6000MAXQ, 96 GB VRAM."""
    ...

def RTX_PRO_6000S(count: int = 1) -> Accelerator:
    """RTX-PRO-6000S, 96 GB VRAM."""
    ...

def RTX_PRO_6000WK(count: int = 1) -> Accelerator:
    """RTX-PRO-6000WK, 96 GB VRAM."""
    ...

def RTX_PRO_6000WS(count: int = 1) -> Accelerator:
    """RTX-PRO-6000WS, 96 GB VRAM."""
    ...

def RTX_PRO_SERVER_6000(count: int = 1) -> Accelerator:
    """RTX-PRO-SERVER-6000, 96 GB VRAM."""
    ...

def T4(count: int = 1) -> Accelerator:
    """T4, 16 GB VRAM."""
    ...

def T4G(count: int = 1) -> Accelerator:
    """T4G, 16 GB VRAM."""
    ...

def TITAN_RTX(count: int = 1) -> Accelerator:
    """TITAN-RTX, 24 GB VRAM."""
    ...

def TITAN_V(count: int = 1) -> Accelerator:
    """TITAN-V, 12 GB VRAM."""
    ...

def TITAN_XP(count: int = 1) -> Accelerator:
    """TITAN-XP, 12 GB VRAM."""
    ...

def TPU_V2(count: int = 1) -> Accelerator:
    """TPU-V2, 8 GB VRAM."""
    ...

def TPU_V2_8(count: int = 1) -> Accelerator:
    """TPU-V2-8, 64 GB VRAM."""
    ...

def TPU_V3(count: int = 1) -> Accelerator:
    """TPU-V3, 16 GB VRAM."""
    ...

def TPU_V3_32(count: int = 1) -> Accelerator:
    """TPU-V3-32, 512 GB VRAM."""
    ...

def TPU_V3_8(count: int = 1) -> Accelerator:
    """TPU-V3-8, 128 GB VRAM."""
    ...

def TPU_V4(count: int = 1) -> Accelerator:
    """TPU-V4, 32 GB VRAM."""
    ...

def TPU_V4_64(count: int = 1) -> Accelerator:
    """TPU-V4-64, 2048 GB VRAM."""
    ...

def TPU_V5E(count: int = 1) -> Accelerator:
    """TPU-V5E, 16 GB VRAM."""
    ...

def TPU_V5E_4(count: int = 1) -> Accelerator:
    """TPU-V5E-4, 64 GB VRAM."""
    ...

def TPU_V5P(count: int = 1) -> Accelerator:
    """TPU-V5P, 95 GB VRAM."""
    ...

def TPU_V5P_8(count: int = 1) -> Accelerator:
    """TPU-V5P-8, 760 GB VRAM."""
    ...

def TPU_V6(count: int = 1) -> Accelerator:
    """TPU-V6, 32 GB VRAM."""
    ...

def TRAINIUM1(count: int = 1) -> Accelerator:
    """TRAINIUM1, 32 GB VRAM."""
    ...

def TRAINIUM2(count: int = 1) -> Accelerator:
    """TRAINIUM2, 64 GB VRAM."""
    ...

def TRAINIUM3(count: int = 1) -> Accelerator:
    """TRAINIUM3, 128 GB VRAM."""
    ...

def V100(count: int = 1) -> Accelerator:
    """V100, 32 GB VRAM."""
    ...


def __getattr__(attribute: str) -> Callable[..., Accelerator]: ...
def __dir__() -> list[str]: ...
