"""Type definitions for distributed collections."""

from __future__ import annotations

from typing import Any, Protocol

from skyward.api.distributed import Consistency as Consistency


class Registry(Protocol):
    """Protocol satisfied by DistributedRegistry and IPCRegistry."""

    def dict(self, name: str, *, consistency: Consistency | None = None) -> Any: ...
    def set(self, name: str, *, consistency: Consistency | None = None) -> Any: ...
    def counter(self, name: str, *, consistency: Consistency | None = None) -> Any: ...
    def queue(self, name: str) -> Any: ...
    def barrier(self, name: str, n: int) -> Any: ...
    def lock(self, name: str, timeout: float = 30) -> Any: ...
    def cleanup(self) -> None: ...
