"""Generate ``skyward/accelerators.pyi`` from the accelerator catalog.

``skyward/accelerators.py`` resolves every name dynamically through
``__getattr__`` against ``CATALOG``, so an IDE sees nothing to complete. This
script turns each catalog entry into a typed factory stub, keeping the
auto-complete surface in step with the one catalog it is derived from.

Run with ``uv run python scripts/gen_accelerators_pyi.py``.
"""

from __future__ import annotations

from pathlib import Path

from skyward.shared.accelerators import CATALOG

STUB_PATH = Path(__file__).resolve().parent.parent / "skyward" / "core" / "accelerators.pyi"

HEADER = '''"""Typed factories for every accelerator in the catalog.

Generated by ``scripts/gen_accelerators_pyi.py`` from
``skyward.shared.accelerators.CATALOG`` — do not edit by hand.
"""

from collections.abc import Callable
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Accelerator:
    """A canonical accelerator name and how many of them a node should have."""

    name: str
    count: int = 1
'''

FOOTER = '''def __getattr__(attribute: str) -> Callable[..., Accelerator]: ...
def __dir__() -> list[str]: ...
'''


def factory_name(catalog_name: str) -> str:
    """The attribute ``accelerators.py``'s ``__dir__`` exposes for a catalog key."""
    return catalog_name.upper().replace("-", "_")


def stub(catalog_name: str) -> str:
    accelerator = CATALOG[catalog_name]
    doc = f"{accelerator.name.upper()}, {accelerator.vram:g} GB VRAM."
    return (
        f"def {factory_name(catalog_name)}(count: int = 1) -> Accelerator:\n"
        f'    """{doc}"""\n'
        f"    ...\n"
    )


def render() -> str:
    factories = "\n".join(stub(name) for name in sorted(CATALOG))
    return f"{HEADER}\n\n{factories}\n\n{FOOTER}"


def main() -> None:
    STUB_PATH.write_text(render())
    print(f"wrote {len(CATALOG)} factories to {STUB_PATH}")


if __name__ == "__main__":
    main()
