"""``sky compute ssh`` and ``sky repl`` — a terminal on one of a compute's machines.

The SSH connections belong to the daemon, so this side never opens one, and never
holds a key: the compute's key was generated by the daemon, handed to the provider
and kept in its store, and none of it is anywhere near this process. What crosses
is bytes. It mints a session id, opens the same pair of half-duplex streams a
forwarded port uses — keystrokes up, whatever the terminal paints down — and spends
the rest of the session copying between them and this process's own terminal.

Which means the local terminal has to stop being clever. In its usual mode the
tty buffers a line, echoes it, and eats Ctrl-C to signal *this* process; all
three belong to the shell at the far end, so the tty is put in raw mode for the
session and put back, whatever happens, when it ends.
"""

from __future__ import annotations

import asyncio
import os
import stat
import sys
import termios
import tty
import uuid
from collections.abc import AsyncIterator, Awaitable, Callable, Iterator
from contextlib import contextmanager, suppress
from typing import Annotated

import httpx
from cyclopts import Parameter

from skyward.cli import app, compute_app
from skyward.cli._client import Work, call
from skyward.core.client import Client
from skyward.core.errors import SkywardError, UnexpectedResponseError
from skyward.worker.bootstrap import PYTHON

CHUNK = 65536

type Painter = Callable[[bytes], Awaitable[None]]
"""What one chunk of what the terminal paints goes through."""

REFUSAL_SECONDS = 5.0
"""How long the down half waits for the up half to say what went wrong.

The two fail together — one dispatch, one refusal — so this is a grace and not a
poll. Past it, whatever ended the session is described as what it looked like from
here, which is a connection that stopped.
"""


@compute_app.command(name="ssh")
def ssh(
    ref: Annotated[str, Parameter(help="A compute id or name")],
    *,
    node: Annotated[int | None, Parameter(help="The rank to open the terminal on; omit for the lowest one the daemon can reach")] = None,
    command: Annotated[str | None, Parameter(help="What to run; omit for the login shell")] = None,
    url: Annotated[str | None, Parameter(help="Daemon URL")] = None,
) -> None:
    """Open an interactive shell on one of a compute's machines.

    The same machine for the whole session, and the same one again if you name it:
    a terminal is somebody sitting at a computer, not a load-balanced request.

    A machine takes a session as soon as it answers SSH, which is the whole of its
    bootstrap before it is ready — so this is also how you watch one install its
    driver, or find out why it never finished. One still booting is waited for.
    """
    _call(lambda client: _attach(client, ref, node, command), url=url)


app.command(ssh, name="console")


@app.command(name="repl")
def repl(
    ref: Annotated[str, Parameter(help="A compute id or name")],
    *,
    node: Annotated[int | None, Parameter(help="The rank to open the REPL on; omit for the lowest one the daemon can reach")] = None,
    url: Annotated[str | None, Parameter(help="Daemon URL")] = None,
) -> None:
    """Open a Python REPL on one of a compute's machines.

    ``ssh`` with the interpreter the node was bootstrapped with, which is the one
    holding the compute's dependencies — not whatever ``python`` resolves to on a
    machine that was never meant to be logged into.
    """
    ssh(ref, node=node, command=PYTHON, url=url)


@contextmanager
def raw() -> Iterator[None]:
    """Hand this terminal over for the length of a session, and take it back after.

    A pipe is left alone: there is no tty to make raw, and a ``sky compute ssh`` on
    the end of one is a script, which wants its bytes untouched anyway.

    Blocking mode is put back with the rest. Watching the keyboard through the loop
    clears it, and it is a property of the open terminal rather than of this process
    — so a session that ends without restoring it hands the shell underneath a stdin
    that fails its reads.
    """
    if not sys.stdin.isatty():
        yield
        return

    fd = sys.stdin.fileno()
    saved = termios.tcgetattr(fd)
    blocking = os.get_blocking(fd)
    try:
        tty.setraw(fd)
        yield
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, saved)
        os.set_blocking(fd, blocking)


def size() -> tuple[int, int]:
    with suppress(OSError):
        window = os.get_terminal_size()
        return window.columns, window.lines
    return 80, 24


async def _keystrokes() -> AsyncIterator[bytes]:
    """This process's stdin, as it is typed.

    A terminal or a pipe is read through the event loop rather than a thread, so that
    the pump ends when the session does: a blocking read would still be sitting on the
    keyboard long after the shell exited, holding the command open until somebody
    pressed a key.

    Anything else is a redirection, and nobody is typing into one: it is read whole,
    off the loop, and sent in one go.
    """
    if not _watchable():
        with suppress(OSError, ValueError):
            if data := await asyncio.to_thread(sys.stdin.buffer.read):
                yield data
        return

    reader = asyncio.StreamReader()
    loop = asyncio.get_running_loop()
    transport, _ = await loop.connect_read_pipe(lambda: asyncio.StreamReaderProtocol(reader), sys.stdin)
    try:
        while data := await reader.read(CHUNK):
            yield data
    finally:
        transport.close()


def _watchable() -> bool:
    """Whether the loop can watch this stdin for reading.

    A terminal and a pipe it can. A regular file asyncio refuses outright, and on
    macOS the kernel rejects ``/dev/null`` — in a callback, after the transport was
    built, where nothing can catch it and the only trace is a stack printed over the
    session. Both are ``sky compute ssh`` with its input redirected.
    """
    if sys.stdin is None or sys.stdin.closed:
        return False
    with suppress(OSError, ValueError):
        mode = os.fstat(sys.stdin.fileno()).st_mode
        return sys.stdin.isatty() or stat.S_ISFIFO(mode) or stat.S_ISSOCK(mode)
    return False


async def _attach(client: Client, ref: str, rank: int | None, command: str | None) -> None:
    cid = uuid.uuid4().hex
    with raw():
        waiting = _waiting(rank)
        pump = asyncio.create_task(client.shell_up(ref, cid, rank, command, os.environ.get("TERM", "xterm-256color"), size(), _keystrokes()))
        paint = await _painter()
        try:
            async for chunk in client.shell_down(ref, cid):
                if waiting:
                    _erase()
                    waiting = False
                await paint(chunk)
        except httpx.ConnectError:
            raise
        except httpx.HTTPError as dropped:
            raise await _ended(pump, dropped) from None
        finally:
            pump.cancel()
            with suppress(asyncio.CancelledError, Exception):
                await pump


async def _painter() -> Painter:
    """Where what the terminal paints goes.

    Through the loop wherever it can go, because by now the terminal is in
    non-blocking mode: watching the keyboard sets that on the open terminal, and
    stdout is the same open terminal. A plain write to one raises
    ``BlockingIOError`` the moment the far end paints faster than the terminal
    drains it, which is every full-screen redraw. The loop's writer holds the
    overflow and drains it when the terminal is ready for more.

    Output that is not a terminal — redirected to a file, which asyncio will not
    wrap — never went non-blocking, and is written as it always was.
    """
    loop = asyncio.get_running_loop()
    try:
        transport, protocol = await loop.connect_write_pipe(asyncio.streams.FlowControlMixin, sys.stdout.buffer)
    except (OSError, ValueError):
        return _written

    writer = asyncio.StreamWriter(transport, protocol, None, loop)

    async def painted(chunk: bytes) -> None:
        writer.write(chunk)
        await writer.drain()

    return painted


async def _written(chunk: bytes) -> None:
    sys.stdout.buffer.write(chunk)
    sys.stdout.buffer.flush()


def _waiting(rank: int | None) -> bool:
    """Say what is being waited for, while there is nothing else on the screen.

    A machine that is still booting takes the session at the moment it answers,
    which can be a minute of nothing at all — and a terminal showing nothing looks
    like a terminal that hung. Erased by the first byte the far end paints.
    """
    if not sys.stdout.isatty():
        return False
    where = f" on rank {rank}" if rank is not None else ""
    sys.stderr.write(f"opening a terminal{where}...\r")
    sys.stderr.flush()
    return True


def _erase() -> None:
    sys.stderr.write("\r\033[2K")
    sys.stderr.flush()


async def _ended(pump: asyncio.Task[None], dropped: httpx.HTTPError) -> SystemExit:
    """Why the session ended, asked of the half that was told.

    Down only ever sees a body that stopped, which is the symptom and never the
    reason: whatever the daemon refused, it refused on the dispatch, which is up.
    An older daemon refuses there after the stream has already started, and this is
    what turns that into a sentence instead of a protocol error.

    An address with no daemon at all never reaches here — that one is re-raised for
    :mod:`skyward.cli._client`, which knows to say how to start one.
    """
    try:
        async with asyncio.timeout(REFUSAL_SECONDS):
            await asyncio.shield(pump)
    except (SkywardError, UnexpectedResponseError) as refusal:
        return SystemExit(_said(refusal))
    except Exception:
        pass
    return SystemExit(f"the terminal session ended: {dropped}")


def _said(refusal: SkywardError | UnexpectedResponseError) -> str:
    match refusal:
        case SkywardError():
            return f"{refusal.code}: {refusal.message}"
        case UnexpectedResponseError():
            return f"the daemon could not open the terminal — {refusal}"


def _call[T](work: Work[T], *, url: str | None = None) -> T:
    """Run the work, and turn a refusal into a message rather than a traceback."""
    try:
        return call(work, url=url)
    except (SkywardError, UnexpectedResponseError) as refusal:
        raise SystemExit(_said(refusal)) from None
    except httpx.HTTPError as dropped:
        raise SystemExit(f"the daemon stopped answering: {dropped}") from None


__all__ = ["raw", "repl", "size", "ssh"]
