name: Base Image

on:
  push:
    branches: [main]
    paths:
      - 'docker/Dockerfile.base'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build base image
        run: task docker:build PYTHON_VERSION=${{ matrix.python-version }}
      - name: Push base image
        run: task docker:push PYTHON_VERSION=${{ matrix.python-version }}
